defaults:
  - dataset: cityscapes
  - model: segformer_mit-b0
  - optimizer: adamw
  - scheduler: poly
  # - runner: null
  # - augmentations: null
  - _self_

# 최상위에서 공통적으로 쓰이는 설정
seed: 42
gpus: 1
output_dir: ./outputs
device_id: 0
experiment_name: test_cl_dataset_implementation
trainer:
  epochs: 430
  eval_interval: 10

test_checkpoint_path: performance/0903_16:19/1024_1024_0/best_model.pth
test_data_root: data/cityscapes
# test_data_root: data/cityscapes_1536x768

# FL
fl:
  target_resolutions:
    # 0: [1024, 1024]
    # 1: [768, 768]
    # 2: [512, 512]
    0: [512, 512]
    1: [384, 384]
    2: [256, 256]
    # 0: [384, 384]
    # 1: [256, 256]
    # 2: [128, 128]

# loop
val_cfg:
  type: ValLoop

val_evaluator: IoUMetric

# performance/0903_16:20/768_768_1/best_model.pth